/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { SimpleStorageContract } from "./SimpleStorage";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "SimpleStorage"): SimpleStorageContract;
    }
  }
}

export { SimpleStorageContract, SimpleStorageInstance } from "./SimpleStorage";
